# Project configuration list
projects:
  - project_name: Xray
    repo_latest: teddysun/xray
    repo_current: jerryin/xray
    version_source:
      latest: docker_hub
      current: docker_hub
    version_type: semver
    file_path: xray
    repository: xray
    platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6

  - project_name: ZeroTier
    repo_latest: zerotier/ZeroTierOne
    repo_current: jerryin/zerotier
    version_source:
      latest: github_api
      current: docker_hub
    version_type: semver
    file_path: zerotier
    repository: zerotier
    platforms: linux/amd64,linux/arm64

  - project_name: ZeroTier Moon
    repo_latest: zerotier/ZeroTierOne
    repo_current: jerryin/zerotier-moon
    version_source:
      latest: github_api
      current: docker_hub
    version_type: semver
    file_path: zerotier-moon
    repository: zerotier-moon
    platforms: linux/amd64,linux/arm64

  - project_name: n8n
    repo_latest:
      - n8n-io/n8n
      - other-blowsnow/n8n-i18n-chinese
    repo_current: jerryin/n8n
    version_source:
      latest: github_api
      current: docker_hub
    version_type: multi_repo_match
    file_path: n8n
    repository: n8n
    platforms: linux/amd64,linux/arm64

  - project_name: iPerf
    repo_latest: esnet/iperf
    repo_current: jerryin/iperf3
    version_source:
      latest: github_api
      current: docker_hub
    version_type: semver
    file_path: iperf3
    repository: iperf3
    platforms: linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/arm/v7
