name: Xray Schedule CI

on:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  trigger-xray:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Check Xray latest vs current version
        id: check
        run: |
          chmod +x ./xray/check_xray_versions.sh
          ./xray/check_xray_versions.sh > versions.out

          # Extract output variables
          LATEST_VERSION=$(grep '^latest_version=' versions.out | cut -d= -f2)
          UPDATE_NEEDED=$(grep '^update_needed=' versions.out | cut -d= -f2)

          echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          echo "update_needed=$UPDATE_NEEDED" >> $GITHUB_OUTPUT

      - name: Trigger Docker CI workflow via API
        if: steps.check.outputs.update_needed == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'docker-ci.yml',
              ref: 'main',
              inputs: {
                file_path: 'xray',
                repository: 'xray',
                tag: '${{ steps.check.outputs.latest_version }}',
                platforms: 'linux/amd64, linux/arm64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6'
              }
            });

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 3
